language: julia
julia:
  - 0.7
  
matrix:
  - PYTHON=Conda-python

notifications:
  email: false
  
addons:
  apt:
    packages:
      - libcfitsio3
      - gfortran
      - mpich
      - libmpich-dev
      - curl

before_install:
  - julia -e 'ENV["PYTHON"]=""; using Pkg; Pkg.rm("CorrNoise"); Pkg.rm("Healpix"); Pkg.add("PyCall"); Pkg.build("PyCall"); Pkg.add("Conda"); using Conda; Conda.update(); Conda.add("astropy")'
  
after_success:
  - julia -e 'cd(Pkg.dir("Stripeline")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Stripeline")); include(joinpath("docs", "make.jl"))'
